#!/usr/bin/python
import sys,os

# To add "A","B","C"... etc
if len(sys.argv)<2:
    print "Usage:$0 in.pdb [in_acm.pdb]"
    sys.exit()
infile=sys.argv[1]
infile,outfile = ( sys.argv+[infile[:-4]+"_acm.pdb",] )[1:3]

ifp=open(infile,"r")
ofp=open(outfile,"w")

chain=ord("A")
for line in ifp:
    linetype=line[:6].strip()
    if line.find("WAT")!= -1:
        newline=line
    elif linetype == "TER":
        chain=chain+1  # ###############    
        newline = line
    elif linetype == "ATOM":
        newline = line[:21]+chr(chain)+line[22:]
    else:
        newline = line
    ofp.write(newline)
ofp.close()
ifp.close()
