#!/usr/bin/python
import sys,os
import re

if len(sys.argv)<2:
	print "usage: $0  in.top [outtopfile]"
	sys.exit(0)
sys.argv.append("topfile")
infile,outfile=sys.argv[1:3]

format="%6d%11s%7s%7s%7s%8s%11s%11s\n"
pat_atoms=re.compile(r"\[\s*?atoms\s*?\]")
pat_endatoms=re.compile(r"\[\s*?.*?\s*?\]")
flag=False
n=1

ofp=open(outfile,"w")
for line in open(infile,"r"):
    if not line.strip() or line.strip()[0]==";": continue 
    if re.match(pat_atoms,line):
        print line
        flag=True
    elif re.match(pat_endatoms,line):
        print line
        flag=False
    if flag:
        if line[0]==";": continue 
        items=line.split()
        if len(items)>=8:
            tmp="amber99_%s"%(items[1])
            newline=format%(n,tmp,items[2],items[3],items[4],items[5],items[6],items[7])
            n+=1
            ofp.write(newline)
        elif len(items)==7:
            tmp="amber99_%s"%(items[1])
            newline=format%(n,tmp,items[2],items[3],items[4],items[5],items[6],'0.00')
            ofp.write(newline)
    else:
        pass
ofp.close()


