#!/usr/bin/python
import sys,os 

minimparam='''\
file datadir ~/Software/plop21.0/data
file logfile %s
load pdb %s &
  het yes &
  ions yes &
  wat yes &
  opt yes
minim &
  res file res.list &
  mxitn %d &
  verbose yes
structure write %s
'''
tmpfile="sefleisjflseifjsefejsielfjsliefj"

if len(sys.argv)<2:
    print "Usage: $0 file_to_minim [output file]"
    sys.exit()
infile,outfile=(sys.argv[1:]+["f.pdb"])[:2] 

ofp=open(tmpfile,"w")
ofp.write(minimparam%("minim.log",infile,500,outfile))
ofp.close()

os.system('''echo %s |~/Software/plop21.0/plop'''%(tmpfile,))
os.remove(tmpfile)

