#!/usr/bin/python
import sys,os 
import random

minimparam='''\
file datadir ~/Software/plop21.0/data
file logfile %s
load pdb %s &
  het yes &
  ions yes &
  wat yes &
  opt yes
minim &
  res all res &
  mxitn %d &
  verbose yes
structure write %s
'''
tmpfile="sefleisjflseifjsefejsielfjsliefj"+str(random.randint(0,999))

if len(sys.argv)<2:
    print "Usage: $0 file_to_minim [output file]"
    sys.exit()

infile,outfile,logfile=(sys.argv[1:]+["f.pdb"]+["minim.log"])[:3] 

ofp=open(tmpfile,"w")
ofp.write(minimparam%(logfile,infile,500,outfile))
ofp.close()

os.system('''echo %s |~/Software/plop21.0/plop'''%(tmpfile,))
os.remove(tmpfile)

