#!/usr/bin/python
import sys,os 

addhparam='''\
file datadir /home/fuqy/Software/plop21.0/data
file logfile %s
load pdb %s &
  het yes &
  ions yes &
  wat yes &
  opt yes 
structure write %s
'''
tmpfile="sefleisjflseifjsefejsielfjsliefj"

if len(sys.argv)<2:
    print "Usage: $0 file_to_addH [output file]"
    sys.exit()
infile,outfile=(sys.argv[1:]+["f.pdb"])[:2] 

ofp=open(tmpfile,"w")
ofp.write(addhparam%("addh.log",infile,outfile))
ofp.close()

os.system('''echo %s |plop'''%(tmpfile,))
os.system('''rm %s'''%(tmpfile,))


